language: java
jdk:
 - oraclejdk11
before_install:
 - chmod +x mvnw
deploy:
 provider: heroku
 api_key:
  secure: "wR/GAwx41nxEd72ySrRH1SbkZT0A4I13hlxnQR6AwxsLwOK9SWtLoWzNdyV+LVCB3Ed7Zy21fhekf3AeFbrbG91qEHoEEaGHHFflY/SeBBepzsQGVucK72BQnQFiBDGa9lWNyegFjVrwqbtuTeUYsKG5rpHmOSkERvnjN+kl9bqKld7QU/qNWWIC8UhhYU1Ef9efmCTZaA1WK7ApYAY/ldgg9pPwUrM/X3FhEYyPzRr
  SrE+OOor61XeVKp2bZ0M2MgjVYFG4UZMzUuxBvvAMi3y1Z8gTURZs4DJcT6moYhZ2e5nE+dnq0nHWjNm9KRJJkY2B5Iw60kwf+6qAGnvicp6PP3P7v67OOPeEQOVaFED2gE7tCFMnDQNSn8fIW/2vQ3YtccwCO3RB8/FzoN5thmi3yBKpBiXwhwi5ljoQT+dRrfxfPzJogpmbZKVVAmJEEakH/oMz+oQf8ReLkY6EKgedelGf8Fl0w
  sWyeDI00Ua6PTCIIrgNeqwOulCnvawPtxhWNMAAUYyaPCjwp/Q3oVPwgfrxdMetRld4Bz4A1TKvjRUY/16eO9az3w9xJxvcZYujwGlux8W3gBf8ERm56gLmc78poIzUj/+ZENXM8/4Hp8pTl6IDXyUYk9U/GLcuPjn6+Vsai1mf1ngg+LahMwMvzyjGIIb579JgmvR0HA4="
 app: survey-monkey-sysc4806